<?php

namespace Travidence\Rest\Application;


use Nette;
use Nette\Application\Routers\RouteList;

class Router extends RouteList
{
    public function match(Nette\Http\IRequest $httpRequest)
    {
        $req = parent::match($httpRequest);
        if(!$req) {
            return null;
        }

        $name = $req->getPresenterName();
        $method = $req->getMethod();
        $params = $req->getParameters();
        $post = $req->getPost();
        $files = $req->getFiles();

        // fixme: ow-wow!
        $flagsThief = \Closure::bind(function (Nette\Application\Request $request) {
            return $request->flags;
        }, null, Nette\Application\Request::class);
        $flags = $flagsThief($req);

        $request = new Request($name, $method, $params, $post, $files, $flags);
        $request->setRawBodyCallback([$httpRequest, 'getRawBody']);


        return $request; // TODO: Change the autogenerated stub
    }

}
