<?php

namespace Travidence\Rest\Controllers;


use Travidence\Entity\Person;
use Travidence\Entity\Trip;
use Travidence\Entity\TripSegment;
use Travidence\Model\Parser\TripParser;

class TripController extends ARestController
{
    /** @var TripParser */
    public $tripParser;

    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        $this->tripParser = new TripParser();
    }

    public function actionGet()
    {
        $trip = new Trip();

        $person = new Person();
        $person->setName("Bořek");
        $person->setSurname("Stavitel");
        $person->setDepartment("Whoop whoop");
        $person->setWorkStation("Stattiooon");

        $trip->setTraveller($person);


        $trip->setSegments([
            new TripSegment()
        ]);

        $trip->setNote("Yalalala");

        return $trip->asArray();
    }

    public function actionPost()
    {
        $data = $this->request->getJsonBody();
        $trip = $this->tripParser->parseTrip($data['trip']);
        dump($trip);
        dump($trip->asArray());
        exit;
    }
}